## Definição de determinante:
Fixada uma linha $i$ de uma matriz quadrada $A_{nxn} = (a_{ij}) \in M_n(\mathbb{R})$, definimos o determinante de $A$ pela expressão:

$$ \sum_{j=1}^n a_{ij} \cdot (-1)^{i+j} \cdot det\text{A}_{-i,-j}$$

Onde $\text{A}_{-i,-j}$ é a matriz resultante da remoção da linha $i$ e coluna $j$

In [3]:
import numpy as np
import sys

In [223]:
def calcular_determinante(matriz):
    detM = 0
    (ordem, _) = matriz.shape
    
    if ordem == 2:
        return determinante_2(matriz)
    for i in range(0, ordem):
        sub_matriz = np.delete(np.delete(matriz, 0, 0), i, 1)
        print(sub_matriz)
        determinante_inferior = calcular_determinante(sub_matriz)
        detM += matriz[0][i] * (-1)**(i) * determinante_inferior
        print(matriz[0][i] * (-1)**(i))
    return detM

def determinante_2(matriz):
    dp = 1
    ds = 1 
    for i in matriz.diagonal():
        dp *= i
    for i in matriz[::-1].diagonal():
        ds *= i
    return dp - ds

In [233]:
a = np.arange(25).reshape(5,5)

In [234]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [235]:
c = np.delete(a, 0,0)
c = np.delete(c, 2,1)
c

array([[ 5,  6,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 18, 19],
       [20, 21, 23, 24]])

In [236]:
calcular_determinante(a)

[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]
[[12 13 14]
 [17 18 19]
 [22 23 24]]
[[18 19]
 [23 24]]
12
[[17 19]
 [22 24]]
-13
[[17 18]
 [22 23]]
14
6
[[11 13 14]
 [16 18 19]
 [21 23 24]]
[[18 19]
 [23 24]]
11
[[16 19]
 [21 24]]
-13
[[16 18]
 [21 23]]
14
-7
[[11 12 14]
 [16 17 19]
 [21 22 24]]
[[17 19]
 [22 24]]
11
[[16 19]
 [21 24]]
-12
[[16 17]
 [21 22]]
14
8
[[11 12 13]
 [16 17 18]
 [21 22 23]]
[[17 18]
 [22 23]]
11
[[16 18]
 [21 23]]
-12
[[16 17]
 [21 22]]
13
-9
0
[[ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]
 [20 22 23 24]]
[[12 13 14]
 [17 18 19]
 [22 23 24]]
[[18 19]
 [23 24]]
12
[[17 19]
 [22 24]]
-13
[[17 18]
 [22 23]]
14
5
[[10 13 14]
 [15 18 19]
 [20 23 24]]
[[18 19]
 [23 24]]
10
[[15 19]
 [20 24]]
-13
[[15 18]
 [20 23]]
14
-7
[[10 12 14]
 [15 17 19]
 [20 22 24]]
[[17 19]
 [22 24]]
10
[[15 19]
 [20 24]]
-12
[[15 17]
 [20 22]]
14
8
[[10 12 13]
 [15 17 18]
 [20 22 23]]
[[17 18]
 [22 23]]
10
[[15 18]
 [20 23]]
-12
[[15 17]
 [20 22]]
13
-9
-1
[[ 5  6  8  9]
 [10 1

0

In [228]:
b = np.array([[2,5,1,3],[0,-1,4,2],[6,-2,5,1],[1,3,-3,0]])

In [229]:
b

array([[ 2,  5,  1,  3],
       [ 0, -1,  4,  2],
       [ 6, -2,  5,  1],
       [ 1,  3, -3,  0]])

In [230]:
calcular_determinante(b)

[[-1  4  2]
 [-2  5  1]
 [ 3 -3  0]]
[[ 5  1]
 [-3  0]]
-1
[[-2  1]
 [ 3  0]]
-4
[[-2  5]
 [ 3 -3]]
2
2
[[ 0  4  2]
 [ 6  5  1]
 [ 1 -3  0]]
[[ 5  1]
 [-3  0]]
0
[[6 1]
 [1 0]]
-4
[[ 6  5]
 [ 1 -3]]
2
-5
[[ 0 -1  2]
 [ 6 -2  1]
 [ 1  3  0]]
[[-2  1]
 [ 3  0]]
0
[[6 1]
 [1 0]]
1
[[ 6 -2]
 [ 1  3]]
2
1
[[ 0 -1  4]
 [ 6 -2  5]
 [ 1  3 -3]]
[[-2  5]
 [ 3 -3]]
0
[[ 6  5]
 [ 1 -3]]
1
[[ 6 -2]
 [ 1  3]]
4
-3


60